# # Instruction
# - assign a new image name
# - make this file consistent with that in https://github.com/okatsn/MyTeXLife
version: "3.2"

services:
  devtj:
    build:
      context: ..
      #     That is out of /.devcontainer
      # context: .
      #     That is /.devcontainer
      dockerfile: .devcontainer/Dockerfile
      args:
        JULIA_PKG_DEVDIR: /home/jovyan/.julia/dev # just let it be default. See [JULIA_PKG_DEVDIR](https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_PKG_DEVDIR). Be aware that some tests will depend on JULIA_PKG_DEVDIR.
        # SUB_PROJECT_DIR is defined in my-tex-life
    image: latexjuliadev
    init: true
    # See https://docs.docker.com/compose/compose-file/compose-file-v3/#init
    container_name: tex-with-julia
    volumes:
      # # The home directory is called "workspace"; try `cd ..` and `ls` to figure it out.
      - ../:/workspace
      # # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # # SSH directory
      - ~/.ssh:/home/jovyan/.ssh
      # For Windows without WSL, a copy will be made from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # # Shell history persistence
      - ~/.zsh_history:/home/jovyan/.zsh_history:z
      # # Git config
      - ~/.gitconfig:/home/jovyan/.gitconfig
      # # Persistent volumes for this container; Avoid reinstall vscode extensions
      - julia-depot:/home/jovyan/.julia
      #
      # # KEYNOTE: volume for vscode extensions
      # # **A Named Volume**: Docker manages the volume and associates it with the specified path inside the container (/home/jovyan/.vscode-server). It can help avoid permission issues, as Docker handles the ownership and permissions of the volume. The data may not be as easily accessible from the host, as it is managed by Docker. For every named volume, the name should be added to global volumes as below.
      - vscode-server:/home/jovyan/.vscode-server
      # # **A Bind Mount**: This mounts the `~/.vscode-server` in host (e.g., \\wsl.localhost\Ubuntu-20.04\home\okatsn\.vscode-server) into `/home/jovyan/.vscode-server` in the container. Adding/Removing VSCode extensions in either VSCode WSL (Ctrl+Shift+P Open Folder in WSL) or in VSCode Dev. container will result in the change of the host machine's ~/.vscode-server (you can take a look at how .vscode-server/extensions/extensions.json changed).
      # - ~/.vscode-server:/home/jovyan/.vscode-server
      # # Noted the context of the local host (i.e., WSL) is different from that in the container;
      # # this is why there is an additional `~/` here for the host (on the left).

    environment:
      - TZ=TW
      # Set time zone
      # entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]
    entrypoint: sh -c "sleep infinity"
# KEYNOTE: Those defined volumes in service should be declared in the root level
# Unbind vscode-server to volumes to ensure extensions in devcontainer.json to be installed on rebuild
volumes:
  julia-depot:
  vscode-server:
